# Generated by Django 3.2.5 on 2021-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myloc',
            name='medical_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myloc',
            name='police_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myloc',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
